In [141]:
import numpy as np
print dir(np.version)
print np.version.version
print np.version.short_version
#dir(np)


['__builtins__', '__doc__', '__file__', '__name__', '__package__', 'full_version', 'git_revision', 'release', 'short_version', 'version']
1.12.1
1.12.1


In [22]:
a = np.array([1,2,3,4,5,6,7,8,9,0],dtype = 'int64')
print a.dtype
print a


int64
[1 2 3 4 5 6 7 8 9 0]


In [31]:
print np.arange(10,30,5)

print np.arange(10,20,2)
print np.arange(10,1,-1)

[10 15 20 25]
[10 12 14 16 18]
[10  9  8  7  6  5  4  3  2]


In [34]:
print np.arange(10,dtype="float64")

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [38]:
print np.arange(10,110,10,dtype="uint64").reshape(2,5)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [39]:
print np.arange(10).reshape(5,2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [40]:
print np.arange(24).reshape(2,3,4)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [57]:
a = np.arange(100)
print a
print a**2
print  "###############"
b = np.arange(8).reshape(2,4)
print b*10

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
[   0    1    4    9   16   25   36   49   64   81  100  121  144  169  196
  225  256  289  324  361  400  441  484  529  576  625  676  729  784  841
  900  961 1024 1089 1156 1225 1296 1369 1444 1521 1600 1681 1764 1849 1936
 2025 2116 2209 2304 2401 2500 2601 2704 2809 2916 3025 3136 3249 3364 3481
 3600 3721 3844 3969 4096 4225 4356 4489 4624 4761 4900 5041 5184 5329 5476
 5625 5776 5929 6084 6241 6400 6561 6724 6889 7056 7225 7396 7569 7744 7921
 8100 8281 8464 8649 8836 9025 9216 9409 9604 9801]
###############
[[ 0 10 20 30]
 [40 50 60 70]]


In [69]:
print np.zeros(10)
print np.zeros((3,4))
print np.zeros_like(b)
print np.zeros_like(a)
print np.eye(5,k=1)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[0 0 0 0]
 [0 0 0 0]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.]]


In [93]:
e = np.identity(4)
print e
e[1][3]+=10
print "_______"
print e[1,2]
print e[:]

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
_______
0.0
[[  1.   0.   0.   0.]
 [  0.   1.   0.  10.]
 [  0.   0.   1.   0.]
 [  0.   0.   0.   1.]]


In [97]:
data = np.random.rand(3,3,4)
print data

[[[ 0.99033306  0.21908326  0.49748424  0.66215534]
  [ 0.70760576  0.05011433  0.33329773  0.90533365]
  [ 0.5483192   0.21904316  0.85712681  0.93986303]]

 [[ 0.01063204  0.67320299  0.04169611  0.88913825]
  [ 0.07142793  0.74439412  0.02405783  0.74366903]
  [ 0.07803041  0.59388521  0.52033554  0.5135202 ]]

 [[ 0.97364787  0.46515533  0.73611084  0.47733575]
  [ 0.61951638  0.27197892  0.26594253  0.77372666]
  [ 0.47257112  0.6836063   0.32435039  0.92575981]]]


In [98]:
print np.random.randn(8,2)

[[ 0.1771125  -0.44409912]
 [ 0.76939964 -0.30430496]
 [-0.65632611  0.32200657]
 [ 0.92032627 -1.84762839]
 [ 0.35150755  0.8451096 ]
 [ 0.26222244  0.10058722]
 [-0.45070665 -1.0936514 ]
 [ 0.52714953  0.71393971]]


In [100]:
print np.random.randint(3,5,size=(3,4))

[[4 4 4 3]
 [3 4 3 3]
 [4 4 3 3]]


In [105]:
print np.random.random_integers(3,5+1,size=(4,3))
### 不赞成使用此方法  已过时

[[3 5 5]
 [5 5 6]
 [3 6 4]
 [4 6 5]]


d:\ProgramData\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(3, 6 + 1) instead
  """Entry point for launching an IPython kernel.


In [107]:
print b.shape
print b.shape[0]

(2L, 4L)
2


In [116]:
x=np.arange(9).reshape(3,3)
print x
y = np.eye(3,3,dtype="int64")
print y

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [119]:
print np.hstack([x,y])
print np.vstack([x,y])
### 矩阵合并 水平  垂直合并两种

[[0 1 2 1 0 0]
 [3 4 5 0 1 0]
 [6 7 8 0 0 1]]
[[0 1 2]
 [3 4 5]
 [6 7 8]
 [1 0 0]
 [0 1 0]
 [0 0 1]]


In [120]:
print np.linspace(0,10,9)

[  0.     1.25   2.5    3.75   5.     6.25   7.5    8.75  10.  ]


In [123]:
print np.linspace(0,10,9,dtype='int64').reshape(3,3)

[[ 0  1  2]
 [ 3  5  6]
 [ 7  8 10]]


In [134]:
def jsf(i,j):
    return i*j

js = np.fromfunction(jsf,(10,10),dtype="int32")
print js
#久久乘法表
print js[1:,1:]
#http://www.cnblogs.com/smallpi/p/4550361.html

[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  6  7  8  9]
 [ 0  2  4  6  8 10 12 14 16 18]
 [ 0  3  6  9 12 15 18 21 24 27]
 [ 0  4  8 12 16 20 24 28 32 36]
 [ 0  5 10 15 20 25 30 35 40 45]
 [ 0  6 12 18 24 30 36 42 48 54]
 [ 0  7 14 21 28 35 42 49 56 63]
 [ 0  8 16 24 32 40 48 56 64 72]
 [ 0  9 18 27 36 45 54 63 72 81]]
[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]


## 矩阵乘法 n*n = (n*m) X (m*n )
### 转置  array.transpose()  或  array.T
### 逆 numpy.linalg 包 inv 函数
### 最大值 最小值 array.max(axis=0)
### 获取最大最小元素所在位置 array.argmax()
### 平均值 array.mean()函数
### 方差函数为var(),方差函数var()相当于函数mean(abs(x - x.mean())**2),其中x为矩阵
###  标准差标准差的函数为std()相当于sqrt(mean(abs(x - x.mean())**2))，或相当于sqrt(x.var())。
### 中值的函数是median()，调用方法为numpy.median(x,[axis])，axis可指定轴方向，默认axis=None，对所有数去中值。
### 矩阵求和的函数是sum()，
### 矩阵求累积和的函数是cumsum()，
